// 08-settings/Root.jsx
// 이것도 다른 micro-app 에서 온거다
// 어디서 온지 어떻게 알까?
// 어디서 주는거지?
// public interface
// -> 메인 파일!
import { getNavHeightPx } from "navbar";

export default function Root() {
  // Wrong: Not below the navbar
  // return <h1>React settings page</h1>

  // Correct: Below the navbar
  // Example use of cross-microfrontend imports
  return (
    <h1 style={{ marginTop: getNavHeightPx() + "px" }}>React settings page</h1>
  );
}

// 08-home/Root.vue
<template>
  <!-- Wrong: The home page won't be below the fixed navbar -->
  <!-- <h1>Vue Home Page</h1> -->

  <!-- Correct: position home below the navbar, using cross-microfrontend imports  -->
  <BelowNav>
    <div class="home">
      <h1>Vue Home page</h1>
    </div>
  </BelowNav>
</template>
<script>
// 이 BelowNav는 다른 micro-app 에서 왔다
// -> cross micro-frontend import
import { BelowNav } from "navbar";

export default {
  components: {
    BelowNav,
  },
};
</script>
<style scoped>
.home {
  background-color: lightseagreen;
}
</style>
